### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by MeycL** [d-gcc/LightTS#1]
![image](https://user-images.githubusercontent.com/96134259/235683175-ce54ee9c-ed86-4295-8576-13f194e08aed.png)
Thank you very much for your wonderful work. How can I solve this issue when I am trying to reproduce it?

**Comment by MeycL** [comment]
![image](https://user-images.githubusercontent.com/96134259/235683747-be4aa0c0-77a0-4b55-a317-2f33dc3e782e.png)
This is my command.

**Comment by d-gcc** [comment]
Thanks for your interest. The issue is because the teachers are not generated yet, so use the option --experiment "teacher" to save the files and then run the student evaluations.
